[package]
name = "bazalbuilder/dash-community"
description = "A fork of Dash."
authors = ["hcollins", "Bazalbuilder (fork)"]
version = "2.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/Bazalbuilder/Flash"

[dev-dependencies]
Lunit = "bazalbuilder/lunit@0.1.2-alpha"
